---
title: "Prep Discount Model"
output: html_document
date: "2024-10-09"
---

# General Info
This script contains loading data and preprocessing it for all modeling analyses. Crucially (and different to preprocesing in the behavioural analyses), we change the format of fixations in 2.3 and set some parameters in 3 this results in data_prep.RData


### 1 Preperations
#### 1.1 Load Data
```{r}
#clear working environment
rm(list=ls())

#clear all plots
if(!is.null(dev.list())) dev.off()

load("discount_modeling_data.RData")

```

```{r}
# recoding function
recode_fixation <- function(x) {
  case_when(
    x == 1 ~ 3,
    x == 2 ~ 4,
    x == 3 ~ 1,
    x == 4 ~ 2,
    TRUE ~ x  # Keep = unchanged
  )
}

# Apply to dataframes
data_discount_hungry_long$fixElement2 <- recode_fixation(data_discount_hungry_long$fixElement)
data_discount_sated_long$fixElement2 <- recode_fixation(data_discount_sated_long$fixElement)

```


```{r}
#loop over subjects to get the data and arrange it in the order needed
uID <- unique(data_discount_hungry$subject)
#value - time data
valueA <- c()
valueB <- c()
timeA <- c()
timeB <- c()

fixProp1 <- c()
fixProp2 <- c()
fixProp3 <- c()
fixProp4 <- c()
RT <- c()

H <- c() #whether trial is hungry (1) or sated (0)
P <- c() #participant number (from 1 till nsubj, so 1, 2, 3, 4, ..., nsubj)

blubb <- matrix(NA,nrow=max(uID),ncol=2) # check if fixation props are correct
dt <- 1/1000

for (s in (unique(data_discount_hungry$subject))){
  
  #loop over sessions (1 = hungry)
  for (t in 1:2){
    if (t == 1){ #session-specific stuff up front
      sub <- data_discount_hungry[data_discount_hungry$subject == s, ] #hungry
      #fixatedElement <- expanded_table_h[[which(unique(data_discount_hungry$subject)==s)]]
    } else {
      sub <- data_discount_sated[data_discount_sated$subject == s, ] #sated
      #fixatedElement <- expanded_table_s[[which(unique(data_discount_sated$subject)==s)]]
    }
    
    #rearrange input data for value -time Choice
    valueL <- (sub$value_left<sub$value_right) #whether impatient choice was left
    response <- sub$response
    response <- as.numeric(((response==("left"))&(valueL==T))|((response==("right"))&(valueL==F)))
    rt_s <- sub$RT*dt
    rt_s[response==0] = -rt_s[response==0] #dwiener function in JAGS wants "negative" rt if choice == 0

    valueA_s <- sub$value_left*(valueL==T)+sub$value_right*(valueL==F)
    valueB_s <- sub$value_left*(valueL==F)+sub$value_right*(valueL==T)
    timeA_s <- sub$time_left*(valueL==T)+sub$time_right*(valueL==F)
    timeB_s <- sub$time_left*(valueL==F)+sub$time_right*(valueL==T)
    
    fixProp1_s <- sub$valueleft_time/(sub$valueleft_time+sub$valueright_time+sub$timeleft_time+sub$timeright_time) #value left
    fixProp2_s <- sub$valueright_time/(sub$valueleft_time+sub$valueright_time+sub$timeleft_time+sub$timeright_time)#value right
    fixProp3_s <- sub$timeleft_time/(sub$valueleft_time+sub$valueright_time+sub$timeleft_time+sub$timeright_time)#time left
    fixProp4_s <- sub$timeright_time/(sub$valueleft_time+sub$valueright_time+sub$timeleft_time+sub$timeright_time)#time right

    
    #fill in "all-subject" vectors for value time
    valueA <- c(valueA,valueA_s)
    valueB <- c(valueB,valueB_s)
    timeA <- c(timeA,timeA_s)
    timeB <- c(timeB,timeB_s)

    fixProp1 <- c(fixProp1,fixProp1_s)
    fixProp2 <- c(fixProp2,fixProp2_s)
    fixProp3 <- c(fixProp3,fixProp3_s)
    fixProp4 <- c(fixProp4,fixProp4_s)
    
    RT <- c(RT,rt_s)
    H <- c(H,rep(t==1,length(rt_s)))
    P <- c(P,rep(which(uID==s),length(rt_s)))

  }
}

#rescale value and nutri values to lie between 1 and 10 (as in Yang & Krajbich), in line with Berkowitsch et al. 2015
valueA <- (1+((valueA-min(valueA))*(10-1))/(max(valueA)-min(valueA))) 
valueB <- (1+((valueB-min(valueB))*(10-1))/(max(valueB)-min(valueB)))
timeA <- (1+((timeA-min(timeA))*(10-1))/(max(timeA)-min(timeA)))
timeB <- (1+((timeB-min(timeB))*(10-1))/(max(timeB)-min(timeB)))

#reverse rating order so higher is better 
timeA2 <- max(timeA)-timeA
timeB2 <- max(timeB)-timeB

#take only trials with fixations
validT <- which((is.na(fixProp1)==0)|(is.na(fixProp2)==0)|(is.na(fixProp3)==0)|(is.na(fixProp4)==0))
valueA <- valueA[validT]
valueB <- valueB[validT]
timeA <- timeA[validT]
timeB <- timeB[validT]
timeA2 <- timeA2[validT]
timeB2 <- timeB2[validT]
fixProp1 <- fixProp1[validT]
fixProp2 <- fixProp2[validT]
fixProp3 <- fixProp3[validT]
fixProp4 <- fixProp4[validT]
RT <- RT[validT]
H <- H[validT]
P <- P[validT]
N <- length(RT)
S <- length(unique(data_discount_hungry$subject))
```

```{r}
save.image('data_discount_prep.RData')
```