---
title: "Prep social Model"
output: html_document
date: "2024-10-09"
---

# General Info
This script contains loading data and preprocessing it for all modeling analyses. Crucially (and different to preprocesing in the behavioural analyses), we change the format of fixations in 2.3 and set some parameters in 3 this results in data_prep.RData

### 1 Preperations
#### 1.1 Load Data
```{r}
#clear working environment
rm(list=ls())

#clear all plots
if(!is.null(dev.list())) dev.off()

load("social_modeling_data.RData")
#load("food_data.RData")

#check what happened to this one participant in the trial based file!
data_social_hungry_long <- subset(data_social_hungry_long, subject %in% data_social_sated$subject)
data_social_sated_long <- subset(data_social_sated_long, subject %in% data_social_hungry$subject)

```

```{r}
#loop over subjects to get the data and arrange it in the order needed
uID <- unique(data_social_hungry$subject)
#value - ngo data
selfA <- c()
selfB <- c()
ngoA <- c()
ngoB <- c()

fixProp1 <- c()
fixProp2 <- c()
fixProp3 <- c()
fixProp4 <- c()
RT <- c()

H <- c() #whether trial is hungry (1) or sated (0)
P <- c() #participant number (from 1 till nsubj, so 1, 2, 3, 4, ..., nsubj)

blubb <- matrix(NA,nrow=max(uID),ncol=2) # check if fixation props are correct
dt <- 1/1000

for (s in (unique(data_social_hungry$subject))){
  
  #loop over sessions (1 = hungry)
  for (t in 1:2){
    if (t == 1){ #session-specific stuff up front
      sub <- data_social_hungry[data_social_hungry$subject == s, ] #hungry
      #fixatedElement <- expanded_table_h[[which(unique(data_social_hungry$subject)==s)]]
    } else {
      sub <- data_social_sated[data_social_sated$subject == s, ] #sated
      #fixatedElement <- expanded_table_s[[which(unique(data_social_sated$subject)==s)]]
    }
    
    #rearrange input data for self -ngo Choice
    selfL <- (sub$self_left>sub$self_right) #whether selfish choice was left
    response <- sub$response
    response <- as.numeric(((response==("left"))&(selfL==T))|((response==("right"))&(selfL==F)))
    rt_s <- sub$RT*dt
    rt_s[response==0] = -rt_s[response==0] #dwiener function in JAGS wants "negative" rt if choice == 0

    selfA_s <- sub$self_left*(selfL==T)+sub$self_right*(selfL==F)
    selfB_s <- sub$self_left*(selfL==F)+sub$self_right*(selfL==T)
    ngoA_s <- sub$ngo_left*(selfL==T)+sub$ngo_right*(selfL==F)
    ngoB_s <- sub$ngo_left*(selfL==F)+sub$ngo_right*(selfL==T)
    
    fixProp1_s <- sub$selfleft_time/(sub$selfleft_time+sub$selfright_time+sub$ngoleft_time+sub$ngoright_time) #self left
    fixProp2_s <- sub$selfright_time/(sub$selfleft_time+sub$selfright_time+sub$ngoleft_time+sub$ngoright_time)#self right
    fixProp3_s <- sub$ngoleft_time/(sub$selfleft_time+sub$selfright_time+sub$ngoleft_time+sub$ngoright_time)#ngo left
    fixProp4_s <- sub$ngoright_time/(sub$selfleft_time+sub$selfright_time+sub$ngoleft_time+sub$ngoright_time)#ngo right

    
    #fill in "all-subject" vectors for self ngo
    selfA <- c(selfA,selfA_s)
    selfB <- c(selfB,selfB_s)
    ngoA <- c(ngoA,ngoA_s)
    ngoB <- c(ngoB,ngoB_s)

    fixProp1 <- c(fixProp1,fixProp1_s)
    fixProp2 <- c(fixProp2,fixProp2_s)
    fixProp3 <- c(fixProp3,fixProp3_s)
    fixProp4 <- c(fixProp4,fixProp4_s)
    
    RT <- c(RT,rt_s)
    H <- c(H,rep(t==1,length(rt_s)))
    P <- c(P,rep(which(uID==s),length(rt_s)))
    
    #bla=cor.test(as.numeric(fixProps[,1]-fixProps[,2]+fixProps[,3]-fixProps[,4]),as.numeric(rt_s>0))
    #blubb[s,t]=bla$estimate
    
  }
}

#rescale self and nutri selfs to lie between 1 and 10 (as in Yang & Krajbich), in line with Berkowitsch et al. 2015
selfA <- (1+((selfA-min(selfA))*(10-1))/(max(selfA)-min(selfA))) 
selfB <- (1+((selfB-min(selfB))*(10-1))/(max(selfB)-min(selfB)))
ngoA <- (1+((ngoA-min(ngoA))*(10-1))/(max(ngoA)-min(ngoA)))
ngoB <- (1+((ngoB-min(ngoB))*(10-1))/(max(ngoB)-min(ngoB)))

#take only trials with fixations
validT <- which((is.na(fixProp1)==0)|(is.na(fixProp2)==0)|(is.na(fixProp3)==0)|(is.na(fixProp4)==0))
selfA <- selfA[validT]
selfB <- selfB[validT]
ngoA <- ngoA[validT]
ngoB <- ngoB[validT]
fixProp1 <- fixProp1[validT]
fixProp2 <- fixProp2[validT]
fixProp3 <- fixProp3[validT]
fixProp4 <- fixProp4[validT]
RT <- RT[validT]
H <- H[validT]
P <- P[validT]
N <- length(RT)
S <- length(unique(data_social_hungry$subject))
```

```{r}
save.image('data_social_prep.RData')
```
